apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capston
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capston
    spec:
      containers:
        - image: dinatahoun/devops-capstone
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 80
